// src/services/pdfService.js
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

const escapeHtml = (text = "") =>
  String(text)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");

const buildMedicinesMarkup = (prescription) => {
  if (Array.isArray(prescription.medicinesStructured)) {
    return prescription.medicinesStructured
      .map(
        (med) =>
          `<li><strong>${escapeHtml(med.name)}</strong>${
            med.dosage ? ` — ${escapeHtml(med.dosage)}` : ""
          }${med.frequency ? ` | ${escapeHtml(med.frequency)}` : ""}${
            med.days ? ` | ${escapeHtml(med.days)} days` : ""
          }</li>`,
      )
      .join("");
  }

  if (prescription.medicines) {
    return prescription.medicines
      .split(",")
      .map((med) => `<li>${escapeHtml(med.trim())}</li>`)
      .join("");
  }

  return "<li>No medicines prescribed</li>";
};

export const generatePrescriptionPDF = async (prescription) => {
  try {
    const prescribedDate = prescription.createdAt
      ? new Date(prescription.createdAt.seconds * 1000).toLocaleDateString()
      : new Date().toLocaleDateString();

    const htmlContent = `
      <html>
        <body style="font-family: Arial; padding: 20px;">
          <div style="text-align:center; margin-bottom: 20px;">
            <h1 style="color:#1B5E20;">AyurSutra</h1>
            <p style="color: gray;">Ayurvedic Healthcare</p>
          </div>

          <div style="margin-bottom: 15px;">
            <p><strong>Doctor:</strong> ${escapeHtml(prescription.doctorName)}</p>
            <p><strong>Specialization:</strong> ${escapeHtml(
              prescription.doctorSpecialization || "Ayurvedic Specialist",
            )}</p>
            <p><strong>Patient:</strong> ${escapeHtml(prescription.patientName)}</p>
            <p><strong>Date:</strong> ${escapeHtml(prescribedDate)}</p>
            <p><strong>Verification Code:</strong> ${escapeHtml(
              prescription.verificationCode || "Not available",
            )}</p>
          </div>

          <hr />

          <div style="margin-top: 15px;">
            <h3 style="color:#1B5E20;">Diagnosis</h3>
            <p>${escapeHtml(prescription.diagnosis)}</p>
          </div>

          <div style="margin-top: 15px;">
            <h3 style="color:#1B5E20;">Medicines</h3>
            <ul>${buildMedicinesMarkup(prescription)}</ul>
          </div>

          <div style="margin-top: 15px;">
            <h3 style="color:#1B5E20;">Notes</h3>
            <p>${escapeHtml(prescription.notes || "No additional notes")}</p>
          </div>

          <div style="margin-top: 40px; border-top: 1px solid #ddd; padding-top: 16px;">
            <p><strong>Digitally Signed By:</strong> ${escapeHtml(
              prescription.doctorName || "Doctor",
            )}</p>
            <p style="font-size: 12px; color: #475569;">
              Signature Hash: ${escapeHtml(
                `${prescription.digitallySignedBy || "NA"}|${prescription.verificationCode || "NA"}|${prescribedDate}`,
              )}
            </p>
            <p style="font-size: 12px; color: #475569;">
              This document is generated by AyurSutra and can be verified using the prescription code.
            </p>
          </div>
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html: htmlContent });

    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(uri);
    } else {
      alert("Sharing not available on this device");
    }
  } catch (error) {
    console.log("PDF Error:", error);
  }
};
